### ISSUE TITLE
Notification framework

### ISSUE THREAD

**Issue by aliasfalse** [Warframe-Community-Developers/genesis#1]
need a system for receiving and sending notifications from an event-emitter for handling worldstate alerts

**Comment by crunchyintheory** [comment]
Perhaps you could subscribe to updates from [this](http://content.warframe.com/dynamic/rss.php), it's a lot smaller than the worldState feed and it only shows alerts and Invasions.

**Comment by aliasfalse** [comment]
Only problem there is we can't notify about everything else.
