### ISSUE TITLE
Join-able roles selected with reactions

### ISSUE THREAD

**Issue by DJNeonNight** [Warframe-Community-Developers/genesis#77]
NEW suggestion (April 8th)
Add a /rank list, /rank add, /rank remove, etc. to add join-able roles, /rank list would show the first 18 roles with a reaction linked to each of them, then 2 more reactions would serve to change pages (if there were more than 18 roles), when the user that used the command selects a role by clicking on the reaction the message would get edited/deleted, and it would only count for the user that used the command.

Alternatively there could be a /rank permanent-list that would work the same way but it would work for every user (without the page changing part, it should select the page instead (/rank permanent-list 1 for page 1)).

OLD suggestion
It could be a command to add roles to a join-able list, and then a /rank list command to show each 20 of them in a message with a reaction linked to get them, and when the user select one it gets the role and the messages gets deleted/edited, it would only count the user that used the command.

**Comment by ScruffyRules** [comment]
You could allow anyone to do it, thus less spam.

**Comment by aliasfalse** [comment]
I don't think i'll do it with reactions, reason being that i'll have to store and track each of those messages for tracking reactions, and that's a lot of events to even just check, each message that gets reactions on each server. i like the idea, and it sounds novel, but i don't think it'd work out.

I'll probably do just the standard `/join`, `/leave`, `/add rank`, `/remove rank`

**Comment by aliasfalse** [comment]
done, just not with reactions
