### ISSUE TITLE
Multi-platform tracking

### ISSUE THREAD

**Issue by DJNeonNight** [Warframe-Community-Developers/genesis#82]
I was thinking on a way to track alerts/anything from multiple platforms using the /platform command to change platform but not tracking, like you use /track reactor then /platform ps4 and then /track reactor again but this time it adds PS4 alerts to the channel along with the PC alerts.
I don't know if that's even possible but just an idea (this would be useful with updates and maybe news)

**Comment by aliasfalse** [comment]
That flow is too complicated and people would get lost very fast trying to know what platform they were on with what is being tracked.
