### ISSUE TITLE
Archwing Alert Pings for Eximus Scans

### ISSUE THREAD

**Issue by VoltageKg** [Warframe-Community-Developers/genesis#87]
I would like to see a way for a rank of @ArchwingScans to be setup and ping members of this group everytime an Archwing Alert is active (not submersible). This would help the players who need Quanta Ranger Eximus scans on Salacia, Neptune alerts and other Eximus archwing enemies that only appear in alerts.

**Comment by aliasfalse** [comment]
I'll add something on there that if it's archwing it'll show on the embed, but it's not one of the things that we track
