### ISSUE TITLE
/arcane Command

### ISSUE THREAD

**Issue by Silarious** [Warframe-Community-Developers/genesis#88]
I would like a simple /arcane command to show you what it does, for e.g. 
/arcane grace 
Rank 1:
ON DAMAGED: 1.5% chance for +1% Health Regeneration Per Second for 1.5 seconds
Rank 2:
ON DAMAGED: 3% chance for +2% Health Regeneration Per Second for 3 seconds
etc.
And then Drop Sources which for Arcane Grace would be LOR/NMLOR
It could just show a picture of the stats and the source if that's any easier for you.

--EDIT--
Also could you possibly add the rarity of said arcane in the command?

Thank you for your time and consideration of this suggestion!

-Silarious

**Comment by aliasfalse** [comment]
done 👍

**Comment by aliasfalse** [comment]
didn't do by-rank because it would've spread it out a lot more

**Comment by aliasfalse** [comment]
I even colored them by rarity:
![image](https://cloud.githubusercontent.com/assets/7128721/25581859/d16e9a00-2e4f-11e7-8ecd-a2b8e2e0bfef.png)

**Comment by Silarious** [comment]
Ok awesome thanks!
